settings:
  username: emiliojes
  commit_msg: "âš¡ Update README with recent activity"
  max_lines: 5

messages:
  push: "â¬†ï¸ Pushed to {REPO}"
  issues: "â— Opened issue in {REPO}"
  pull_request: "ğŸ”§ Opened PR in {REPO}"
  release: "ğŸš€ Released {REPO}"
  fork: "ğŸ´ Forked {REPO}"
  star: "â­ Starred {REPO}"
